export const appText = {
    "en": {
        day: "days",
        hour: "hours",
        minute: "minutes",
        second: "seconds",
        loading: "Loading...",
        doko: "Doko?",
        lastSeen: "Last seen ",
        ago: " ago",
        about: "🛈 About",
        sourceCode: "Source Code",
        affiliation: "Not affiliated with Hololive Production",
        lastStream: "Last Stream",
        live: "is live now!",
        next: "Next stream",
        in: "in",
        english: "ENG",
        japanese: "日本語",
    },
    "ja": {
        day: `日`,
        hour: "時間",
        minute: "分",
        second: "秒",
        loading: "読み込み中...",
        doko: "どこ？",
        lastSeen: "最後の配信",
        ago: "",
        about: "🛈 サイトについて",
        sourceCode: "ソースコード",
        affiliation: "ホロライブプロダクションとは無関係です",
        lastStream: "最後の配信:",
        live: "が現在配信中！",
        next: "次の配信",
        in: "あと",
        english: "ENG",
        japanese: "日本語",
    }

}